[package]
name = "evops-uniffi"
edition = "2024"

[dependencies]
evops-markdown = { workspace = true, features = ["uniffi"] }

uniffi = { workspace = true, features = ["cli"] }

[lints]
workspace = true
