[package]
name = "evops-pb-ext"
edition = "2024"

[dependencies]
evops-models = { workspace = true }
prost = { workspace = true }  # Needed by build.rs.

[build-dependencies]
prost-build = { workspace = true }
